#!/usr/bin/env bash

set -xe

check_cmd() {
	command -v "$1" || {
		echo "$1 command not found"
		exit 1
	}
}

git::config_default() {
	git config --global --get "$1" || git config --global "$1" "$2"
}

check_cmd git
check_cmd curl
check_cmd jq
check_cmd yq
git::config_default user.email action@github.com
git::config_default user.name github-actions
git::config_default gc.auto 0

pre_prepare() {
	true
}

prepare() {
	true
}

post_prepare() {
	true
}

. "common/lib.sh"
# shellcheck source=/dev/null
. "config/$REMOTE.sh"
# shellcheck source=/dev/null
. "impl/$SYNCER_TYPE.sh"

"pre_prepare"
git init --initial-branch=sync "$GIT_W"
"prepare"
"post_prepare"
