#!/usr/bin/env bash

set -xe

check_cmd() {
	command -v "$1" || {
		echo "$1 command not found"
		exit 1
	}
}

git::config_default() {
	git config --global --get "$1" || git config --global "$1" "$2"
}

check_cmd git
check_cmd curl
check_cmd jq
check_cmd yq
git::config_default user.email action@github.com
git::config_default user.name github-actions
git::config_default gc.auto 0

. "common/lib.sh"
. "impl/impls.sh"
. "config/common.sh"
# shellcheck source=/dev/null
. "config/$REMOTE.sh"

try_call_func "$SYNCER_TYPE::pre_prepare"
git init --initial-branch=sync "$GIT_W" || true
try_call_func "$SYNCER_TYPE::prepare"
try_call_func "$SYNCER_TYPE::post_prepare"
