#!/usr/bin/env bash

set -xe

pre_sync() {
	true
}

post_sync() {
	true
}

. "common/lib.sh"
# shellcheck source=/dev/null
. "config/$REMOTE.sh"
# shellcheck source=/dev/null
. "impl/$SYNCER_TYPE.sh"

"pre_sync"
"sync"
"post_sync"
