#!/usr/bin/env bash

set -E

. common/lib.sh
. impl/impls.sh
. config/common.sh
# shellcheck source=/dev/null
. "config/$REMOTE.sh"

try_call_func "$SYNCER_TYPE::pre_sync"
try_call_func "$SYNCER_TYPE::sync"
try_call_func "$SYNCER_TYPE::post_sync"
