#!/usr/bin/env bash

set -xe

. "common/lib.sh"
. "impl/impls.sh"
. "config/common.sh"
# shellcheck source=/dev/null
. "config/$REMOTE.sh"

try_call_func "$SYNCER_TYPE::pre_sync"
try_call_func "$SYNCER_TYPE::sync"
try_call_func "$SYNCER_TYPE::post_sync"
