#!/usr/bin/env bash

set -e

# shellcheck source=../common/lib.sh
. "./common/lib.sh"

git::refs::fetch tools "$1"

while read -r ref; do
	if [[ "$ref" == *^{} ]]; then
		continue
	fi
	echo "Deleting ref $ref"
	wgit push --force "$1" :"$ref"
done < <(git::refs::withprefix tools "$2")

git::refs::delete tools

echo Done
