name: Sync

on:
  push:
    branches: [main]
  schedule:
    - cron: "30 13 * * *"
  workflow_dispatch:

jobs:
  codeberg:
    runs-on: ubuntu-latest
    env:
      REMOTE: codeberg
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: ./prepare_actions; ./prepare
      - name: Sync
        run: ./sync
      - name: Push
        run: ./push

  exogit:
    runs-on: ubuntu-latest
    env:
      REMOTE: exogit
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: ./prepare_actions; ./prepare
      - name: Sync
        run: ./sync
      - name: Push
        run: ./push
