name: Sync

on:
  push:
    branches: [main]
  schedule:
    - cron: "30 13 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  codeberg:
    runs-on: ubuntu-latest
    env:
      REMOTE: codeberg
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: ./prepare_actions; ./prepare
      - name: Sync
        run: ./sync
      - name: Push
        run: ./push

  codeberg-xvnet:
    runs-on: ubuntu-latest
    env:
      REMOTE: codeberg-xvnet
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: ./prepare_actions; ./prepare
      - name: Sync
        run: ./sync
      - name: Push
        run: ./push

  exogit:
    runs-on: ubuntu-latest
    env:
      REMOTE: exogit
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: ./prepare_actions; ./prepare
      - name: Sync
        run: ./sync
      - name: Push
        run: ./push
